# Generated by Django 2.2.25 on 2021-12-08 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['posted'], 'verbose_name': 'Новости', 'verbose_name_plural': 'Статья'},
        ),
        migrations.AlterField(
            model_name='news',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 8, 13, 7, 38, 643257), verbose_name='Опубликовано'),
        ),
        migrations.AlterModelTable(
            name='news',
            table='News',
        ),
    ]
